Add tests for aabstract graph basic methods
spbu-coding-2023/graphs-graph-2 pull request #21
Opened 2024-05-14 22:53 UTC by kar1mgh

Add parameterized tests for all basic methods of abstract graph, they are tested on all it inheritors.

2024-05-15 13:14 UTC, qrutyy approved these changes

2024-05-15 13:30 UTC, spisladqo commented on app/src/test/kotlin/model/abstractGraph/GraphTest.kt
> +                    assertEquals(expectedVertices, actualVertices)
It doesn't work as expected, please remake it everywhere it appears .

2024-05-15 13:33 UTC, spisladqo requested changes
Sadly, every parametrized test falls.

And some of the assertions will always be false, because Vertex and Edge are classes, but not data classes, so `equals()` compares hashes of these objects. I don't think we need to make them data classes, because tests can be remade to work as expected.

2024-05-15 13:44 UTC, kar1mgh commented
> Sadly, every parametrized test falls.
> 
> And some of the assertions will always be false, because Vertex and Edge are classes, but not data classes, so `equals()` compares hashes of these objects. I don't think we need to make them data classes, because tests can be remade to work as expected.

Very helpful remarks, thank you!! I'll try to fix it ASAP

2024-05-15 22:23 UTC, kar1mgh commented
Fixed everything, parameterized tests work as it was intended. Found a bug in removeVertexFromEverywhere method, we are trying to change set while iterating over it. TODO: fix this bug.

2024-05-15 23:27 UTC, kar1mgh commented
FIxed found bug in another PR, found new bug))). Everything in tests work as intended. PR is ready to be merged.
TODO: fix found bug.

2024-05-16 05:41 UTC, qrutyy approved these changes
Nice! 
As i understood, the found bug is already fixed in another PR, but in TODO you mentioned to fix another one?
Pls comment, what bug you need to fix)

2024-05-16 06:35 UTC, kar1mgh commented
> Nice! 
> As i understood, the found bug is already fixed in another PR, but in TODO you mentioned to fix another one?
> Pls comment, what bug you need to fix)

Yes, there is another one, wil fix it in the same #26 PR.

2024-05-16 17:50 UTC, spisladqo approved these changes
Good job!

2024-05-18 10:09 UTC, merged