Enforce graph visualisation, add T-FDP layout, improve UI/UX
spbu-coding-2023/graphs-graph-2 pull request #42
Opened 2024-05-23 19:47 UTC by qrutyy

#### Enforce graph visualisation, add T-FDP layout, improve UI by adding more elements connected connected to graph representation and fixing added before)

### Main goal - improve the graph representation for better UX.

Thats why I managed to:

- Implement _T-FDP_ layout, that will be customisable by user in future)
- Implement _'add Edge'_ and _'add Vertex'_ methods for user. (yeah, we love them)
- Improve the intuitiveness of the UI by adding _'FAQ'_ button, that displays the type of graph and its stored data type.
- Improve the UX (the more the better) by adding ability to drag the graph and zoom it.
- Display vertices ID
- Correct connection between _View_ and _ViewModel_, so _GraphView_ updates after some changes were made.
- Clean up the file structure

**TODO:** 
- mb optimize layout
- sql connection
- integration tests
- add two other tabs (_FileControl_, _Analyze_)
- make theme switchable

2024-05-23 20:59 UTC, kar1mgh requested changes
Refactor a lil

2024-05-23 20:59 UTC, kar1mgh commented on app/src/main/kotlin/view/graph/GraphView.kt
> +}
No new line in the end of file

2024-05-23 20:59 UTC, kar1mgh commented on app/src/main/kotlin/view/utils/FAQBox.kt
> +}
And here

2024-05-23 20:59 UTC, kar1mgh commented on app/src/main/kotlin/view/utils/ZoomBox.kt
> +}
And here

2024-05-23 20:59 UTC, kar1mgh commented on app/src/main/kotlin/viewmodel/MainScreenViewModel.kt
>      //    fun setEdgeColor
mb remove?

2024-05-23 20:59 UTC, shakareem commented on app/src/main/kotlin/viewmodel/graph/TFDPLayout.kt
> +}
And here

2024-05-24 06:23 UTC, qrutyy commented
> Refactor a lil

Done

2024-05-24 06:54 UTC, kar1mgh approved these changes

2024-05-24 07:28 UTC, spisladqo approved these changes
So good and so helpful!

2024-05-24 07:50 UTC, merged